{% set version = "0.88" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-broman
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/broman_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/broman/broman_{{ version }}.tar.gz
  sha256: 54c8456a89f0a87f766d825908328bb7411e864eec9cd05850a394be332d07e7

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('broman')"           # [not win]
    - "\"%R%\" -e \"library('broman')\""  # [win]

about:
  home: https://github.com/kbroman/broman
  license: GPL-3.0-only
  summary: Miscellaneous R functions, including functions related to graphics (mostly for base graphics), permutation tests, running mean/median, and general utilities.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
